POST http://localhost/atv2/api.php

{
    "nome": "Paulo Pereira",
    "email": "paulo.tor@example.com",
    "senha": "senha123",
    "telefone": "123456789",
    "endereco": "Rua A, 123",
    "nascimento": "2002-01-01"
}